# Generated by Django 4.0.4 on 2022-07-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('manufacturer', models.CharField(max_length=35)),
                ('horsepower', models.IntegerField()),
            ],
        ),
    ]
