# Generated by Django 4.0.4 on 2022-07-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Fueled:')),
                ('fuel', models.CharField(choices=[('A', 'Regular Unleaded'), ('B', 'Premium Unleaded'), ('C', 'Supreme Unleaded'), ('E', 'Ethanol Fuel')], default='A', max_length=1, verbose_name='Fuel Types')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
