# Generated by Django 4.0.4 on 2022-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tires'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tires',
            field=models.ManyToManyField(to='main_app.tires'),
        ),
    ]
